<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


return [
    'exluded_routes' => [
        'admin.api.login',
        'admin.api.forget-password.check-email',
        'admin.api.forget-password.check-otp',
        'admin.api.forget-password.reset',
        'admin.session.destroy',
        'admin.users.me',
        'admin.core.channel.list',
        'admin.core.area.list',
        'admin.core.fetchAll',
        'admin.core.getAll',
        'admin.areas.getAreasWithWarehouses',
        'admin.roles.fetchRoles',
        'admin.app-management.alerts.me',
        'admin.permissions.clear',
        'admin.permissions.build',
        'admin.permissions.translate',
        'admin.queues.generate',
        'admin.core.hashTags',
        'admin.customers.customer.call-with-otp',
        'admin.marketing.promotions.bundles.products-search',
        'admin.customers.customer.device-list',
        'admin.dashboard.overview.overview-summary.itemsOutOfStockByArea',
    ],
    'custom_permissions' => [
        'admin.customers.customer.search',
        'admin.customers.customer.filter-date',
        'admin.customers.customer.filter-area',
        'admin.customers.customer.filter-source',
        'admin.customers.customer.import',
        'admin.customers.customer.export',
        'admin.app-management.banners.filter-area',
        'admin.app-management.products.filter-inventory',
        'admin.app-management.products.import',
        'admin.app-management.products.export',
        'admin.inventory.suppliers.search',
        'admin.customers.customer.can-view-transcations-wallet',
    ],
    'sidebar_routes' => [
        'dashboard' => [
            'order-overview' => 'orders-overview',
            'dashboard-map' => 'map',
            'overview' => 'overview'
        ],
        'customers' => [
            'all-customers' => 'customer'
        ],
        'app-management' => [
            'all-banners' => 'banners',
            'all-notifications' => 'notifications',
            'all-tags' => 'producttags',
            'all-categories' => 'categories',
            'sub-categories-list' => 'sub-categories',
            'all-brands' => 'brands',
            'all-products' => 'products',
        ],
        'orders' => [
            'all-orders' => 'orders'
        ],
        'inventory' => [
            'all-purchase-orders' => 'purchase-order',
            'all-transfers' => 'transactions',
            'all-adjustments' => 'adjustments',
            'all-shelves' => 'shelves',
            'all-suppliers' => 'suppliers',
        ],
        'personal' => [
            'all-drivers' => 'drivers',
            'all-collectors' => 'collectors',
        ],
        'marketing' => [
            'all-sms-campaigns' => 'sms-campaigns',
            'all-notifications' => 'notifications',
            'all-promotions' => 'promotions',
        ],
        'accounting' => [
            'all-area-transactions' => 'area-transactions',
            'all-accountant-transactions' => 'accountant-transactions',
            'all-drivers-transactions' => 'driver-transactions',
        ],
        'settings' => [
            'all-admins' => 'users',
            'all-roles' => 'roles',
            'all-logs' => 'logs',
            'all-areas' => 'areas',
        ],
    ],
    'sidebar_main' => [
        'dashboard' => [
            'orders-overview' => 'order-overview',
            'map' => 'dashboard-map',
            'overview' => 'overview'
        ],
        'customers' => [
            'customer' => 'all-customers'
        ],
        'app-management' => [
            'banners' => 'all-banners',
            'categories' => 'all-categories',
            'sub-categories' => 'sub-categories-list',
            'brands' => 'all-brands',
            'producttags' => 'all-tags',
            'productlabels' => 'all-productlabels',
            'products' => 'all-products',
            'alerts' => 'all-alerts'
        ],
        'orders' => [
            'order' => 'all-orders'
        ],
        'inventory' => [
            'purchase-order' => 'all-purchase-orders',
            'transactions' => 'all-transfers',
            'adjustments' => 'all-adjustments',
            'suppliers' => 'all-suppliers',
            'shelves' => 'all-shelves',
        ],
        'personal' => [
            'drivers' => 'all-drivers',
            'collectors' => 'all-collectors',
        ],
        'marketing' => [
            'sms-campaign' => 'all-sms-campaigns',
            'notifications' => 'all-notifications',
            'promotions' => 'all-promotions',
        ],
        'accounting' => [
            'area-transactions' => 'all-area-transactions',
            'accountant-transactions' => 'all-accountant-transactions',
            'driver-transactions' => 'all-drivers-transactions',
        ],
        'settings' => [
            'users' => 'all-admins',
            'roles' => 'all-roles',
            'logs' => 'all-logs',
            'areas' => 'all-areas',
        ],
    ],
    'sidebar_main_routes' => [
        'dashboard',
        'customers',
        'app-management',
        'orders',
        'inventory',
        'personal',
        'marketing',
        'accounting',
        'settings'
    ],
    'sidebar_sub' => [
        'promotions' => [
            'promocodes' => 'all-promo-codes',
            'discounts' => 'all-discounts',
            'bundles' => 'all-bundles'
        ],
    ],
    'sidebar_sub_routes' => ['promotions'],
    'reports' => [
        'super-admin' => [
            'stock-and-sold-specified-products',
            'time-to-zero-report',
            'adjustment-report',
            'amount-collected',
            'operations',
            'inventory-product',
            'inventory-product-ver-2',
            'old-inventory-product-ver-2',
            'inventory-warehouse-amount',
            'inventory-warehouse-stock-value',
            'products-prices',
            'products-sold-count',
            'product-most-sold',
            'stock-and-sold',
            'orders-count',
            'driver-logins',
            'delivery-time-with-order',
            'basket-average',
            // 'basket-average-ver-2',
            'delivery-time-delay-more-than-hour',
            'delivery-time-delay-more-than-two-hour',
            'avg-delivery-time-by-area',
            'orders-per-hour',
            'orders-with-no-books',
            'orders-with-books',
            'orders-count-per-hour-with-delivery-time',
            'prodcuts-with-no-orders',
            'products-with-prices-and-last-po-price',
            'inventory-control',
            'inventory-product-barcode-sku-qty',
            'count-updated-orders-in-area',
            'operation-managers-wallet',
            'drivers-wallet',
            'count-customers-orders',
            "avg-customers-orders",
            'purchase-first-order',
            'purchase-atleast-five-orders',
            'orders-rating',
            'orders-violation',
            'updated-orders-with-no-books',
            'drivers-incentive',
            'robosto-supplier'
            //          'first-order-created-in-month',
            //            'adjustment-cost',
            //            'discount-cost-per',
            //            'discount-cost-val',
            //            'revenue'
        ],
        'area-manager' => [
            'amount-collected',
            // 'operations',
            // 'operation-managers-wallet',
            // 'inventory-product',
            // 'inventory-product-ver-2',
            // 'old-inventory-product-ver-2',
            // 'inventory-warehouse-amount',
            // 'inventory-warehouse-stock-value',
            // 'products-prices',
            // 'products-sold-count',
            // 'product-most-sold',
            // 'stock-and-sold',
            // 'orders-count',
            // 'driver-logins',
            // 'delivery-time-with-order',
            // 'basket-average',
            // // 'basket-average-ver-2',
            // 'delivery-time-delay-more-than-hour',
            // 'delivery-time-delay-more-than-two-hour',
            // 'avg-delivery-time-by-area',
            // 'orders-per-hour',
            // 'orders-with-no-books',
            // 'orders-with-books',
            // 'orders-count-per-hour-with-delivery-time',
            // 'prodcuts-with-no-orders',
            // 'products-with-prices-and-last-po-price',
            // 'inventory-control',
            // 'inventory-product-barcode-sku-qty',
            // 'count-updated-orders-in-area',
            // 'purchase-first-order',
            // 'purchase-atleast-five-orders',
            // 'orders-rating',
            // 'orders-violation',
            // 'updated-orders-with-no-books',
            // 'drivers-incentive',
            // 'robosto-supplier',
            // 'drivers-wallet'
            //          'first-order-created-in-month',
            //            'adjustment-cost',
            //            'discount-cost-per',
            //            'discount-cost-val',
            //            'revenue'
        ],
        'operation-manager' => [
            'stock-and-sold-specified-products',
            'time-to-zero-report',
            'adjustment-report',
            'amount-collected',
            'operations',
            'operation-managers-wallet',
            'inventory-product',
            'inventory-product-ver-2',
            'old-inventory-product-ver-2',
            'inventory-warehouse-amount',
            'inventory-warehouse-stock-value',
            'products-prices',
            'products-sold-count',
            'product-most-sold',
            'stock-and-sold',
            'orders-count',
            'driver-logins',
            'delivery-time-with-order',
            'basket-average',
            // 'basket-average-ver-2',
            'delivery-time-delay-more-than-hour',
            'delivery-time-delay-more-than-two-hour',
            'avg-delivery-time-by-area',
            'orders-per-hour',
            'orders-with-no-books',
            'orders-with-books',
            'orders-count-per-hour-with-delivery-time',
            'prodcuts-with-no-orders',
            'products-with-prices-and-last-po-price',
            'inventory-control',
            'inventory-product-barcode-sku-qty',
            'count-updated-orders-in-area',
            'purchase-first-order',
            'purchase-atleast-five-orders',
            'orders-rating',
            'orders-violation',
            'updated-orders-with-no-books',
            'drivers-incentive',
            'robosto-supplier',
            'drivers-wallet'
            //          'first-order-created-in-month',
            //            'adjustment-cost',
            //            'discount-cost-per',
            //            'discount-cost-val',
            //            'revenue'
        ],
        'data-entery' => [
            'operations',
            'orders-with-no-books',
            'orders-with-books',
            'amount-collected'
        ],
        'cs-manager' => [
            'stock-and-sold-specified-products',
            'time-to-zero-report',
            'adjustment-report',
            'amount-collected',
            'operations',
            'inventory-product',
            'inventory-product-ver-2',
            'old-inventory-product-ver-2',
            'inventory-warehouse-amount',
            'inventory-warehouse-stock-value',
            'products-prices',
            'products-sold-count',
            'product-most-sold',
            'stock-and-sold',
            'orders-count',
            'driver-logins',
            'delivery-time-with-order',
            'basket-average',
            'delivery-time-delay-more-than-hour',
            'delivery-time-delay-more-than-two-hour',
            'avg-delivery-time-by-area',
            'orders-per-hour',
            'orders-with-no-books',
            'orders-with-books',
            'orders-count-per-hour-with-delivery-time',
            'prodcuts-with-no-orders',
            'products-with-prices-and-last-po-price',
            'inventory-control',
            'inventory-product-barcode-sku-qty',
            'count-updated-orders-in-area',
            'operation-managers-wallet',
            'drivers-wallet',
            'count-customers-orders',
            "avg-customers-orders",
            'purchase-first-order',
            'purchase-atleast-five-orders',
            'orders-rating',
            'orders-violation',
            'updated-orders-with-no-books',
            'drivers-incentive',
            'robosto-supplier'
        ],
        'accountant' => [
            'amount-collected',
            'operation-managers-wallet',
            'drivers-wallet',
            'drivers-incentive',
        ],
        'reporter'=>[
            'operations',
            'orders-with-no-books',
            "purchase-first-order"
        ]
    ],
];